// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrintingHouseBackend.Data;

#nullable disable

namespace PrintingHouseBackend.Migrations
{
    [DbContext(typeof(PrintingHouseContext))]
    [Migration("20241005134002_newdata2")]
    partial class newdata2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrintingHouseBackend.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            Company = "Doe Designs",
                            Country = "USA",
                            Email = "john.doe@doedesigns.com",
                            Name = "John",
                            PhoneNumber = "+1-123-456-7890",
                            PostalCode = "10001",
                            State = "NY",
                            StreetAddress = "123 Main St",
                            Surname = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            City = "Los Angeles",
                            Company = "Smith Printing Co.",
                            Country = "USA",
                            Email = "jane.smith@smithprinting.com",
                            Name = "Jane",
                            PhoneNumber = "+1-987-654-3210",
                            PostalCode = "90001",
                            State = "CA",
                            StreetAddress = "456 Elm St",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            City = "Miami",
                            Company = "Gonzalez Graphics",
                            Country = "USA",
                            Email = "maria.gonzalez@gonzalezgraphics.com",
                            Name = "Maria",
                            PhoneNumber = "+1-555-123-4567",
                            PostalCode = "33101",
                            State = "FL",
                            StreetAddress = "789 Oak St",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            Id = 4,
                            City = "London",
                            Country = "UK",
                            Email = "liam.brown@example.co.uk",
                            Name = "Liam",
                            PhoneNumber = "+44-20-7946-0958",
                            PostalCode = "SW1A 2AA",
                            State = "England",
                            StreetAddress = "10 Downing Street",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = 5,
                            City = "Sydney",
                            Company = "Taylor Marketing",
                            Country = "Australia",
                            Email = "emily.taylor@taylormarketing.au",
                            Name = "Emily",
                            PhoneNumber = "+61-2-9374-4000",
                            PostalCode = "2000",
                            State = "NSW",
                            StreetAddress = "100 George St",
                            Surname = "Taylor"
                        },
                        new
                        {
                            Id = 6,
                            City = "Springfield",
                            Company = "Doe Inc.",
                            Country = "USA",
                            Email = "john.doe@example.com",
                            Name = "John",
                            PhoneNumber = "123-456-7890",
                            PostalCode = "62704",
                            State = "IL",
                            StreetAddress = "123 Main St",
                            Surname = "Doe"
                        },
                        new
                        {
                            Id = 7,
                            City = "Greenville",
                            Company = "Smith LLC",
                            Country = "USA",
                            Email = "jane.smith@example.com",
                            Name = "Jane",
                            PhoneNumber = "234-567-8901",
                            PostalCode = "75401",
                            State = "TX",
                            StreetAddress = "456 Oak St",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = 8,
                            City = "Lincoln",
                            Company = "Johnson Co.",
                            Country = "USA",
                            Email = "alice.johnson@example.com",
                            Name = "Alice",
                            PhoneNumber = "345-678-9012",
                            PostalCode = "68508",
                            State = "NE",
                            StreetAddress = "789 Pine St",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = 9,
                            City = "Columbus",
                            Company = "Brown Enterprises",
                            Country = "USA",
                            Email = "robert.brown@example.com",
                            Name = "Robert",
                            PhoneNumber = "456-789-0123",
                            PostalCode = "43215",
                            State = "OH",
                            StreetAddress = "321 Elm St",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = 10,
                            City = "Hartford",
                            Company = "Davis & Co.",
                            Country = "USA",
                            Email = "emily.davis@example.com",
                            Name = "Emily",
                            PhoneNumber = "567-890-1234",
                            PostalCode = "06103",
                            State = "CT",
                            StreetAddress = "654 Maple Ave",
                            Surname = "Davis"
                        },
                        new
                        {
                            Id = 11,
                            City = "Dover",
                            Company = "Clark Industries",
                            Country = "USA",
                            Email = "michael.clark@example.com",
                            Name = "Michael",
                            PhoneNumber = "678-901-2345",
                            PostalCode = "19901",
                            State = "DE",
                            StreetAddress = "987 Cedar St",
                            Surname = "Clark"
                        },
                        new
                        {
                            Id = 12,
                            City = "Bismarck",
                            Company = "Martinez Ltd.",
                            Country = "USA",
                            Email = "sophia.martinez@example.com",
                            Name = "Sophia",
                            PhoneNumber = "789-012-3456",
                            PostalCode = "58501",
                            State = "ND",
                            StreetAddress = "111 Birch Ln",
                            Surname = "Martinez"
                        },
                        new
                        {
                            Id = 13,
                            City = "Denver",
                            Company = "Lewis Brothers",
                            Country = "USA",
                            Email = "james.lewis@example.com",
                            Name = "James",
                            PhoneNumber = "890-123-4567",
                            PostalCode = "80202",
                            State = "CO",
                            StreetAddress = "222 Spruce St",
                            Surname = "Lewis"
                        },
                        new
                        {
                            Id = 14,
                            City = "Phoenix",
                            Company = "Walker Solutions",
                            Country = "USA",
                            Email = "olivia.walker@example.com",
                            Name = "Olivia",
                            PhoneNumber = "901-234-5678",
                            PostalCode = "85001",
                            State = "AZ",
                            StreetAddress = "333 Ash St",
                            Surname = "Walker"
                        },
                        new
                        {
                            Id = 15,
                            City = "Sacramento",
                            Company = "Hall & Partners",
                            Country = "USA",
                            Email = "david.hall@example.com",
                            Name = "David",
                            PhoneNumber = "012-345-6789",
                            PostalCode = "95814",
                            State = "CA",
                            StreetAddress = "444 Palm Dr",
                            Surname = "Hall"
                        },
                        new
                        {
                            Id = 16,
                            City = "Atlanta",
                            Company = "Young Corp.",
                            Country = "USA",
                            Email = "lucas.young@example.com",
                            Name = "Lucas",
                            PhoneNumber = "321-123-4321",
                            PostalCode = "30303",
                            State = "GA",
                            StreetAddress = "555 Cypress St",
                            Surname = "Young"
                        },
                        new
                        {
                            Id = 17,
                            City = "Austin",
                            Company = "King Enterprises",
                            Country = "USA",
                            Email = "mia.king@example.com",
                            Name = "Mia",
                            PhoneNumber = "432-234-5432",
                            PostalCode = "73301",
                            State = "TX",
                            StreetAddress = "666 Olive St",
                            Surname = "King"
                        },
                        new
                        {
                            Id = 18,
                            City = "Las Vegas",
                            Company = "Scott LLC",
                            Country = "USA",
                            Email = "henry.scott@example.com",
                            Name = "Henry",
                            PhoneNumber = "543-345-6543",
                            PostalCode = "88901",
                            State = "NV",
                            StreetAddress = "777 Pine Rd",
                            Surname = "Scott"
                        },
                        new
                        {
                            Id = 19,
                            City = "Miami",
                            Company = "Green Solutions",
                            Country = "USA",
                            Email = "grace.green@example.com",
                            Name = "Grace",
                            PhoneNumber = "654-456-7654",
                            PostalCode = "33101",
                            State = "FL",
                            StreetAddress = "888 Aspen Ln",
                            Surname = "Green"
                        },
                        new
                        {
                            Id = 20,
                            City = "Seattle",
                            Company = "Hill Group",
                            Country = "USA",
                            Email = "ethan.hill@example.com",
                            Name = "Ethan",
                            PhoneNumber = "765-567-8765",
                            PostalCode = "98101",
                            State = "WA",
                            StreetAddress = "999 Oak Dr",
                            Surname = "Hill"
                        },
                        new
                        {
                            Id = 21,
                            City = "Portland",
                            Company = "Adams LLC",
                            Country = "USA",
                            Email = "ava.adams@example.com",
                            Name = "Ava",
                            PhoneNumber = "876-678-9876",
                            PostalCode = "97201",
                            State = "OR",
                            StreetAddress = "1001 Maple St",
                            Surname = "Adams"
                        },
                        new
                        {
                            Id = 22,
                            City = "Chicago",
                            Company = "Nelson Technologies",
                            Country = "USA",
                            Email = "benjamin.nelson@example.com",
                            Name = "Benjamin",
                            PhoneNumber = "987-789-0987",
                            PostalCode = "60601",
                            State = "IL",
                            StreetAddress = "1102 Willow St",
                            Surname = "Nelson"
                        },
                        new
                        {
                            Id = 23,
                            City = "Boston",
                            Company = "Carter Enterprises",
                            Country = "USA",
                            Email = "ella.carter@example.com",
                            Name = "Ella",
                            PhoneNumber = "098-890-1098",
                            PostalCode = "02108",
                            State = "MA",
                            StreetAddress = "1203 Cedar St",
                            Surname = "Carter"
                        },
                        new
                        {
                            Id = 24,
                            City = "New York",
                            Company = "Mitchell Industries",
                            Country = "USA",
                            Email = "daniel.mitchell@example.com",
                            Name = "Daniel",
                            PhoneNumber = "109-901-2109",
                            PostalCode = "10001",
                            State = "NY",
                            StreetAddress = "1304 Birch Ln",
                            Surname = "Mitchell"
                        },
                        new
                        {
                            Id = 25,
                            City = "San Francisco",
                            Company = "Perez & Co.",
                            Country = "USA",
                            Email = "lily.perez@example.com",
                            Name = "Lily",
                            PhoneNumber = "210-012-3210",
                            PostalCode = "94101",
                            State = "CA",
                            StreetAddress = "1405 Elm St",
                            Surname = "Perez"
                        });
                });

            modelBuilder.Entity("PrintingHouseBackend.Models.JobDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaperType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintSides")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("JobsDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorMode = "Full Color",
                            Dimensions = "3.5x2 inches",
                            Name = "Business Cards",
                            PaperType = "Glossy",
                            Pattern = "BC-001",
                            PrintSides = "Double",
                            UnitPrice = 0.20m
                        },
                        new
                        {
                            Id = 2,
                            ColorMode = "Full Color",
                            Dimensions = "8.5x11 inches",
                            Name = "Flyers",
                            PaperType = "Matte",
                            Pattern = "FL-002",
                            PrintSides = "Single",
                            UnitPrice = 0.15m
                        },
                        new
                        {
                            Id = 3,
                            ColorMode = "Full Color",
                            Dimensions = "18x24 inches",
                            Name = "Posters",
                            PaperType = "Satin",
                            Pattern = "PO-003",
                            PrintSides = "Single",
                            UnitPrice = 2.50m
                        },
                        new
                        {
                            Id = 4,
                            ColorMode = "Full Color",
                            Dimensions = "8.5x11 inches",
                            Name = "Brochures",
                            PaperType = "Glossy",
                            Pattern = "BR-004",
                            PrintSides = "Double",
                            UnitPrice = 1.00m
                        },
                        new
                        {
                            Id = 5,
                            ColorMode = "Full Color",
                            Dimensions = "4x4 inches",
                            Name = "Stickers",
                            PaperType = "Vinyl",
                            Pattern = "ST-005",
                            PrintSides = "Single",
                            UnitPrice = 0.50m
                        },
                        new
                        {
                            Id = 6,
                            ColorMode = "Grayscale",
                            Dimensions = "8.5x11 inches",
                            Name = "Letterheads",
                            PaperType = "Bond",
                            Pattern = "LH-006",
                            PrintSides = "Single",
                            UnitPrice = 0.10m
                        },
                        new
                        {
                            Id = 7,
                            ColorMode = "Full Color",
                            Dimensions = "9.5x4.125 inches",
                            Name = "Envelopes",
                            PaperType = "Standard",
                            Pattern = "EN-007",
                            PrintSides = "Single",
                            UnitPrice = 0.25m
                        },
                        new
                        {
                            Id = 8,
                            ColorMode = "Full Color",
                            Dimensions = "3x6 feet",
                            Name = "Banners",
                            PaperType = "Vinyl",
                            Pattern = "BA-008",
                            PrintSides = "Single",
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            Id = 9,
                            ColorMode = "Grayscale",
                            Dimensions = "5x7 inches",
                            Name = "Notepads",
                            PaperType = "Bond",
                            Pattern = "NP-009",
                            PrintSides = "Single",
                            UnitPrice = 0.50m
                        },
                        new
                        {
                            Id = 10,
                            ColorMode = "Duotone",
                            Dimensions = "11x17 inches",
                            Name = "Calendars",
                            PaperType = "Glossy",
                            Pattern = "CA-010",
                            PrintSides = "Double",
                            UnitPrice = 3.00m
                        });
                });

            modelBuilder.Entity("PrintingHouseBackend.Models.JobOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobDetailsId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobDetailsId");

                    b.ToTable("JobsOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 1,
                            OrderDate = new DateOnly(2024, 9, 20),
                            Quantity = 100,
                            Status = "Pending",
                            TotalPrice = 20m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            DeliveryMethod = "Self Pickup",
                            JobDetailsId = 2,
                            OrderDate = new DateOnly(2024, 9, 21),
                            Quantity = 100,
                            Status = "In Progress",
                            TotalPrice = 15m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 3,
                            OrderDate = new DateOnly(2024, 9, 22),
                            Quantity = 100,
                            Status = "Completed",
                            TotalPrice = 250m
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 4,
                            OrderDate = new DateOnly(2024, 9, 23),
                            Quantity = 100,
                            Status = "Pending",
                            TotalPrice = 100m
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 5,
                            OrderDate = new DateOnly(2024, 9, 24),
                            Quantity = 100,
                            Status = "In Progress",
                            TotalPrice = 50m
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 1,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 1,
                            OrderDate = new DateOnly(2024, 9, 25),
                            Quantity = 100,
                            Status = "Completed",
                            TotalPrice = 500.50m
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 2,
                            DeliveryMethod = "Pickup",
                            JobDetailsId = 2,
                            OrderDate = new DateOnly(2024, 9, 30),
                            Quantity = 200,
                            Status = "Pending",
                            TotalPrice = 1000.00m
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 3,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 3,
                            OrderDate = new DateOnly(2024, 9, 27),
                            Quantity = 150,
                            Status = "Shipped",
                            TotalPrice = 750.75m
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 4,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 4,
                            OrderDate = new DateOnly(2024, 9, 23),
                            Quantity = 300,
                            Status = "Completed",
                            TotalPrice = 1500.00m
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 5,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 5,
                            OrderDate = new DateOnly(2024, 10, 2),
                            Quantity = 250,
                            Status = "Processing",
                            TotalPrice = 1250.25m
                        },
                        new
                        {
                            Id = 11,
                            CustomerId = 6,
                            DeliveryMethod = "Pickup",
                            JobDetailsId = 6,
                            OrderDate = new DateOnly(2024, 9, 20),
                            Quantity = 175,
                            Status = "Shipped",
                            TotalPrice = 875.50m
                        },
                        new
                        {
                            Id = 12,
                            CustomerId = 7,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 7,
                            OrderDate = new DateOnly(2024, 10, 3),
                            Quantity = 100,
                            Status = "Pending",
                            TotalPrice = 500.00m
                        },
                        new
                        {
                            Id = 13,
                            CustomerId = 8,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 8,
                            OrderDate = new DateOnly(2024, 9, 28),
                            Quantity = 220,
                            Status = "Processing",
                            TotalPrice = 1100.00m
                        },
                        new
                        {
                            Id = 14,
                            CustomerId = 9,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 9,
                            OrderDate = new DateOnly(2024, 9, 26),
                            Quantity = 180,
                            Status = "Completed",
                            TotalPrice = 900.00m
                        },
                        new
                        {
                            Id = 15,
                            CustomerId = 10,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 10,
                            OrderDate = new DateOnly(2024, 10, 4),
                            Quantity = 130,
                            Status = "Processing",
                            TotalPrice = 650.50m
                        },
                        new
                        {
                            Id = 16,
                            CustomerId = 11,
                            DeliveryMethod = "Pickup",
                            JobDetailsId = 1,
                            OrderDate = new DateOnly(2024, 9, 24),
                            Quantity = 160,
                            Status = "Completed",
                            TotalPrice = 800.00m
                        },
                        new
                        {
                            Id = 17,
                            CustomerId = 12,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 2,
                            OrderDate = new DateOnly(2024, 9, 21),
                            Quantity = 270,
                            Status = "Shipped",
                            TotalPrice = 1350.75m
                        },
                        new
                        {
                            Id = 18,
                            CustomerId = 13,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 3,
                            OrderDate = new DateOnly(2024, 9, 19),
                            Quantity = 320,
                            Status = "Completed",
                            TotalPrice = 1600.00m
                        },
                        new
                        {
                            Id = 19,
                            CustomerId = 14,
                            DeliveryMethod = "Pickup",
                            JobDetailsId = 4,
                            OrderDate = new DateOnly(2024, 9, 17),
                            Quantity = 140,
                            Status = "Pending",
                            TotalPrice = 700.00m
                        },
                        new
                        {
                            Id = 20,
                            CustomerId = 15,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 5,
                            OrderDate = new DateOnly(2024, 9, 29),
                            Quantity = 190,
                            Status = "Shipped",
                            TotalPrice = 950.00m
                        },
                        new
                        {
                            Id = 21,
                            CustomerId = 16,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 6,
                            OrderDate = new DateOnly(2024, 9, 22),
                            Quantity = 210,
                            Status = "Completed",
                            TotalPrice = 1050.00m
                        },
                        new
                        {
                            Id = 22,
                            CustomerId = 17,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 7,
                            OrderDate = new DateOnly(2024, 9, 18),
                            Quantity = 230,
                            Status = "Processing",
                            TotalPrice = 1150.00m
                        },
                        new
                        {
                            Id = 23,
                            CustomerId = 18,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 8,
                            OrderDate = new DateOnly(2024, 9, 15),
                            Quantity = 300,
                            Status = "Shipped",
                            TotalPrice = 1500.00m
                        },
                        new
                        {
                            Id = 24,
                            CustomerId = 19,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 9,
                            OrderDate = new DateOnly(2024, 9, 13),
                            Quantity = 250,
                            Status = "Pending",
                            TotalPrice = 1250.50m
                        },
                        new
                        {
                            Id = 25,
                            CustomerId = 20,
                            DeliveryMethod = "Courier",
                            JobDetailsId = 10,
                            OrderDate = new DateOnly(2024, 9, 11),
                            Quantity = 120,
                            Status = "Processing",
                            TotalPrice = 600.00m
                        });
                });

            modelBuilder.Entity("PrintingHouseBackend.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jeremy20110@yahoo.com",
                            FirstName = "Jeri",
                            LastName = "Medlin",
                            Password = "123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "heber_barte@gmail.com",
                            FirstName = "Cynthia",
                            LastName = "Chamberlain",
                            Password = "123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "bettie1995@hotmail.com",
                            FirstName = "Justin",
                            LastName = "Smith",
                            Password = "123"
                        });
                });

            modelBuilder.Entity("PrintingHouseBackend.Models.JobOrder", b =>
                {
                    b.HasOne("PrintingHouseBackend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintingHouseBackend.Models.JobDetails", "JobDetails")
                        .WithMany()
                        .HasForeignKey("JobDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("JobDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
